- name: Demonstrates use of list in ansible
  hosts: all
  vars_files:
    - myvariable_file
  tasks:
    - name: Install the softwares in remote Ubuntu containers
      apt: name="{{item}}" state=latest update_cache=yes
      when: ansible_distribution == "Ubuntu"
      with_list: "{{software_packages}}"

    - name: Install the epel release packages for CentOS containers
      yum: name=epel-release state=latest 
      when: ansible_distribution != "Ubuntu" 

    - name: Install the softwares in remote Centos containers
      yum: name="{{item}}" state=latest
      when: ansible_distribution == "CentOS"
      with_list: "{{software_packages}}"
