- name: Install, Configure and Deploy web page into nginx web server
  hosts: all
  vars:
    - greeting_msg: DevOps!
    - provisioner_tool: Docker
    - automation_tool: Ansible
  tasks:
    - name: Install nginx web server
      apt: name=nginx state=present update_cache=yes 
    
    - name: Configure nginx web root folder
      copy: src=default dest=/etc/nginx/sites-available/default

    - name: Create the new nginx web root folder
      shell: "mkdir -p /var/html"

    - name: Restart the nginx web server
#     service: name=nginx state=started
      command: service nginx restart

    - name: Deploy a web page into nginx web server
      template: src=index.html.j2   dest=/var/html/index.html
