- name: Install, Configure and Deploy web page into nginx web server
  hosts: all
  vars:
    - greeting_msg: DevOps!
    - provisioner_tool: Docker
    - automation_tool: Ansible
  tasks:
    - name: Install nginx web server in Ubuntu 
      apt: name=nginx state=present update_cache=yes 
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian")

    - name: Install epel-release package in CentOS
      yum: name=epel-release state=latest
      when: ( ansible_distribution == "CentOS"  and ansible_os_family == "RedHat")

    - name: Install nginx web server in CentOS
      yum: name=nginx state=present
      when: ( ansible_distribution == "CentOS"  and ansible_os_family == "RedHat")
    
    - name: Configure nginx web root folder in Ubuntu
      copy: src=default_ubuntu dest=/etc/nginx/sites-available/default
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian")

    - name: Configure nginx web root folder in CentOS
      copy: src=default_centos.conf dest=/etc/nginx/conf.d/default.conf
      when: ( ansible_distribution == "CentOS"  and ansible_os_family == "RedHat")

    - name: Create the new nginx web root folder
      shell: "mkdir -p /var/html"
      when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS")

    - name: Restart the nginx web server
      command: service nginx restart
      when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS")

    - name: Deploy a web page into nginx web server
      template: src=index.html.j2   dest=/var/html/index.html
      when: ( ansible_distribution == "Ubuntu" or ansible_distribution == "CentOS")









